apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  source:
    repoURL: 'git@github.com:Gologolo97/app-portfolio.git'
    targetRevision: HEAD
    path: flask-chart
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  
  

