apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.3.3
    chart: fluentd
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  