apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.32.15
    chart: grafana
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  