apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-controller
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  source:
    repoURL: 'git@github.com:bitnami/charts.git'
    targetRevision: HEAD
    path: bitnami/nginx-ingress-controller
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  
  

