apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.12.0
    chart: prometheus
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  